name: Build and Push Docker Image

on:
  push:
    branches: [f-v1.18]
    paths:
      - 'dockers/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from package.json
        id: version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockers/teable/Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USER }}/teable:latest
            docker.io/${{ secrets.DOCKER_USER }}/teable:${{ steps.version.outputs.VERSION }}

