name: Integration Tests

on:
  push:
    branches: [f-v1.18]
  pull_request:
    branches: [f-v1.18]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ./.github/actions/pnpm-install
      - run: pnpm g:test-unit

